server:
  port: 8086
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
spring:
  profiles:
    active: dev
  application:
    name: emsp
  datasource:
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        session_factory:
          statement_inspector: com.lenovo.iop.user.auth.infrastructure.config.TenantStatementInterceptor
logging:
  config: classpath:logback-dev.xml